language: python
dist: "xenial"
sudo: true

services:
    # Tricks to avoid matplotlib error about X11:
    # 'no display name and no $DISPLAY environment variable'
    # https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-services-xvfb
    - xvfb
 
# available Python versions:
# https://docs.travis-ci.com/user/languages/python/#Development-releases-support
python:
    - "3.6"
    - "3.7"

before_install:
    # instal lib32 for autoclass
    - sudo apt-get install -y libc6-i386

install:
    - travis_wait make install-dev
    - travis_wait make install-autoclass
    - conda activate autoclasswrapper-dev


before_script:
    # update PATH for AutoClass C
    - export PATH=$PATH:$(pwd)/autoclass-c
    # try to run AutoClass C
    - $TRAVIS_BUILD_DIR/autoclass-c/autoclass

script:
    - make test
