name: autoclasswrapper-dev
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - pip
  - numpy
  - matplotlib
  - pandas
  - scipy
  - chardet
  - jupyter
  - pycodestyle
  - pydocstyle
  - pylint
  - twine
  - bumpversion
  - pytest
  - pytest-cov
  - sphinx
  - nbsphinx
  - sphinx_rtd_theme
  - pip:
    - nbsphinx-link
    - recommonmark
    - sphinx-git
